=== FSopelsa/WT-3/Föreläsningsexempel/F5/F5-ex2/data/xml/vacation.dtd
<!--
vaction_objects
	accommodation+
		attr: type (apartment|cottage)
		size
			rooms
			area?
		description
		image*
			attr: url
			attr: caption?
		address
			town
			country
		price+
			attr: currency

-->

<!ELEMENT vaction_objects (accommodation+)>
	<!ELEMENT accommodation (size, description, image*, address, price)>
			<!ATTLIST accommodation type (apartment|cottage) #REQUIRED>
		<!ELEMENT size (rooms, area?)>
			<!ELEMENT rooms (#PCDATA)>
			<!ELEMENT area (#PCDATA)>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT image EMPTY>
				<!ATTLIST image url CDATA #REQUIRED caption CDATA #IMPLIED>
		<!ELEMENT address (town, country)>
			<!ELEMENT town (#PCDATA)>
			<!ELEMENT country (#PCDATA)>
		<!ELEMENT price (#PCDATA)>
				<!ATTLIST price currency CDATA #REQUIRED>

=== FSopelsa/WT-3/Föreläsningsexempel/F5/F5-ex2/data/xml/denmark.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE vaction_objects SYSTEM "vacation.dtd">

<vaction_objects>

	<accommodation type="apartment">
		<size>
			<rooms>2</rooms>
			<area>62</area>
		</size>
		<description>Trevlig lägenhet på andra våningen. Kakelugn i vardagsrummet.</description>
		<image url="bilder/hus18.jpg"/>
		<address>
			<town>Grøneby</town>
			<country>Danmark</country>
		</address>
		<price currency="DKK">6200</price>
	</accommodation>
	
	<accommodation type="cottage">
		<size>
			<rooms>3</rooms>
		</size>
		<description>Trevlig liten stuga vid kursten.</description>
		<address>
			<town>Strandby</town>
			<country>Danmark</country>
		</address>
		<price currency="DKK">4300</price>
	</accommodation>
	
	<accommodation type="apartment">
		<size>
			<rooms>4</rooms>
		</size>
		<description>Stor och rymlig lägenhet på tredje våningen.</description>
		<address>
			<town>Lilleby</town>
			<country>Danmark</country>
		</address>
		<price currency="DKK">3100</price>
	</accommodation>
	
</vaction_objects>

=== FSopelsa/WT-3/Föreläsningsexempel/F5/F5-ex2/data/xml/england.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE vaction_objects SYSTEM "vacation.dtd">

<vaction_objects>
	
	<accommodation type="cottage">
		<size>
			<rooms>3</rooms>
		</size>
		<description>Ã„ldre hus med modern inredning.</description>
		<address>
			<town>Puddleton</town>
			<country>England</country>
		</address>
		<price currency="GBP">280</price>
	</accommodation>
	
</vaction_objects>

=== FSopelsa/WT-3/Föreläsningsexempel/F5/F5-ex2/data/xml/sweden.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE vaction_objects SYSTEM "vacation.dtd">

<vaction_objects>

	<accommodation type="cottage">
		<size>
			<rooms>4</rooms>
			<area>74</area>
		</size>
		<description>Genuin stuga med gammaldags charm. Ej indraget vatten.</description>
		<image url="bilder/hus47.jpg"/>
		<image url="bilder/hus47plan.gif" caption="planlÃ¶sning"/>
		<address>
			<town>Ekforsen</town>
			<country>Sverige</country>
		</address>
		<price currency="SEK">3400</price>
	</accommodation>
	
	<accommodation type="cottage">
		<size>
			<rooms>3</rooms>
			<area>80</area>
		</size>
		<description>Nyrenoverad stuga med modernt kÃ¶k och badrum.</description>
		<address>
			<town>Bergby</town>
			<country>Sverige</country>
		</address>
		<price currency="SEK">2800</price>
	</accommodation>
	
	<accommodation type="cottage">
		<size>
			<rooms>2</rooms>
			<area>40</area>
		</size>
		<description>Liten mysig stuga med indraget vatten, men utedass.</description>
		<address>
			<town>Skogsby</town>
			<country>Sverige</country>
		</address>
		<price currency="SEK">1900</price>
	</accommodation>
	
</vaction_objects>
