=== FSopelsa/WT-3/L1/games.dtd
<!-- 
game_objects
    game+
        title
        genre+
        year
        developer+
        metascore
        rules
            playerVersus
            numberOfPlayers
            numberOfLives?
        platform+
        moreinfo
            attr: url
-->

<!ELEMENT game_objects (game+)>
    <!ELEMENT game (title, genre+, year, developer+, metascore, rules, platform+, moreinfo)>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT genre (#PCDATA)>
        <!ELEMENT year (#PCDATA)>
        <!ELEMENT developer (#PCDATA)>
        <!ELEMENT metascore (#PCDATA)>
        <!ELEMENT rules (playerVersus, numberOfPlayers, numberOfLives?)>
            <!ELEMENT playerVersus (#PCDATA)>
            <!ELEMENT numberOfPlayers (#PCDATA)>
            <!ELEMENT numberOfLives (#PCDATA)>
        <!ELEMENT platform (#PCDATA)>
        <!ELEMENT moreinfo EMPTY>
            <!ATTLIST moreinfo url CDATA #REQUIRED>

=== FSopelsa/WT-3/L1/shooters.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE game_objects SYSTEM "games.dtd">

<game_objects>

    <game>
        <title>Apex Legends</title>
        <genre>Battle royale</genre>
        <genre>First-person hero shooter</genre>
        <year>2019</year>
        <developer>Respawn Entertainment</developer>
        <metascore>88</metascore>
        <rules>
            <playerVersus>PvP</playerVersus>
            <numberOfPlayers>60</numberOfPlayers>
            <numberOfLives>1</numberOfLives>
        </rules>
        <platform>PC</platform>
        <platform>Nintendo Switch</platform>
        <platform>PlayStation 4</platform>
        <platform>Xbox One</platform>
        <platform>Android, iOS</platform>
        <moreinfo url="https://www.metacritic.com/game/pc/apex-legends" />
    </game>

    <game>
        <title>Counter-Strike: Global Offensive</title>
        <genre>First-person shooter</genre>
        <genre>Tactical team-shooter</genre>
        <year>2012</year>
        <developer>Valve</developer>
        <developer>Hidden Path Entertainment</developer>
        <metascore>83</metascore>
        <rules>
            <playerVersus>PvP</playerVersus>
            <numberOfPlayers>10. (5 på varje lag)</numberOfPlayers>
            <numberOfLives>1 (per runda)</numberOfLives>
        </rules>
        <platform>PC</platform>
        <platform>PlayStation 3</platform>
        <platform>Xbox 360</platform>
        <moreinfo url="https://www.metacritic.com/game/pc/counter-strike-global-offensive" />
    </game>

    <game>
        <title>Doom</title>
        <genre>First-person shooter</genre>
        <genre>Action</genre>
        <year>2016</year>
        <developer>id Software</developer>
        <metascore>85</metascore>
        <rules>
            <playerVersus>PvE/PvP</playerVersus>
            <numberOfPlayers>Upp till 12</numberOfPlayers>
            <numberOfLives>∞</numberOfLives>
        </rules>
        <platform>PC</platform>
        <platform>PlayStation 4</platform>
        <platform>Xbox One</platform>
        <platform>Nintendo Switch </platform>
        <platform>Google Stadia</platform>
        <moreinfo url="https://www.metacritic.com/game/pc/doom" />
    </game>

    <game>
        <title>Portal 2</title>
        <genre>First-person shooter</genre>
        <genre>Puzzle-platform</genre>
        <year>2011</year>
        <developer>Valve</developer>
        <metascore>95</metascore>
        <rules>
            <playerVersus>PvE</playerVersus>
            <numberOfPlayers>1-2</numberOfPlayers>
            <numberOfLives>∞</numberOfLives>
        </rules>
        <platform>PC</platform>
        <platform>PlayStation 3</platform>
        <platform>Xbox 360</platform>
        <moreinfo url="https://www.metacritic.com/game/pc/portal-2" />
    </game>

</game_objects>

=== FSopelsa/WT-3/L1/strategy.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE game_objects SYSTEM "games.dtd">

<game_objects>

    <game>
        <title>Civilization VI</title>
        <genre>Turn-based strategy</genre>
        <year>2016</year>
        <developer>Firaxis Games</developer>
        <metascore>88</metascore>
        <rules>
            <playerVersus>PvE/PvP</playerVersus>
            <numberOfPlayers>Upp till 12</numberOfPlayers>
            <numberOfLives>1</numberOfLives>
        </rules>
        <platform>PC</platform>
        <platform>Nintendo Switch</platform>
        <platform>PlayStation 4</platform>
        <platform>Xbox One</platform>
        <platform>Android</platform>
        <platform>iOS</platform>
        <moreinfo url="https://www.metacritic.com/game/pc/sid-meiers-civilization-vi" />
    </game>

    <game>
        <title>Warcraft III: Reign of Chaos</title>
        <genre>Real-time strategy</genre>
        <year>2002</year>
        <developer>Blizzard Entertainment</developer>
        <metascore>92</metascore>
        <rules>
            <playerVersus>PvE/PvP</playerVersus>
            <numberOfPlayers>Upp till 12</numberOfPlayers>
            <numberOfLives>âˆž</numberOfLives>
        </rules>
        <platform>PC</platform>
        <moreinfo url="https://www.metacritic.com/game/pc/warcraft-iii-reign-of-chaos" />
    </game>

    <game>
        <title>Age of Empires II: The Age of Kings</title>
        <genre>Real-time strategy</genre>
        <year>1999</year>
        <developer>Ensemble Studios</developer>
        <metascore>92</metascore>
        <rules>
            <playerVersus>PvE/PvP</playerVersus>
            <numberOfPlayers>Upp till 8</numberOfPlayers>
            <numberOfLives>1</numberOfLives>
        </rules>
        <platform>PC</platform>
        <platform>PlayStation 2</platform>
        <moreinfo url="https://www.metacritic.com/game/pc/age-of-empires-ii-the-age-of-kings" />
    </game>

    <game>
        <title>StarCraft II: Wings of Liberty</title>
        <genre>Real-time strategy</genre>
        <year>2010</year>
        <developer>Blizzard Entertainment</developer>
        <metascore>93</metascore>
        <rules>
            <playerVersus>PvE/PvP</playerVersus>
            <numberOfPlayers>Upp till 4</numberOfPlayers>
            <numberOfLives>1</numberOfLives>
        </rules>
        <platform>PC</platform>
        <moreinfo url="https://www.metacritic.com/game/pc/starcraft-ii-wings-of-liberty" />
    </game>

</game_objects>

=== FSopelsa/WT-3/L1/storyDriven.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE game_objects SYSTEM "games.dtd">

<game_objects>

    <game>
        <title>Horizon Zero Dawn</title>
        <genre>Action role-playing</genre>
        <genre>Open-World</genre>
        <year>2017</year>
        <developer>Guerrilla Games</developer>
        <metascore>89</metascore>
        <rules>
            <playerVersus>PvE</playerVersus>
            <numberOfPlayers>1</numberOfPlayers>
            <numberOfLives>∞</numberOfLives>
        </rules>
        <platform>PlayStation 4</platform>
        <platform>PC</platform>
        <moreinfo url="https://www.metacritic.com/game/playstation-4/horizon-zero-dawn" />
    </game>

    <game>
        <title>The Last of Us</title>
        <genre>Action-adventure</genre>
        <year>2013</year>
        <developer>Naughty Dog</developer>
        <metascore>95</metascore>
        <rules>
            <playerVersus>PvE</playerVersus>
            <numberOfPlayers>1</numberOfPlayers>
            <numberOfLives>∞</numberOfLives>
        </rules>
        <platform>PlayStation 3</platform>
        <platform>PlayStation 4</platform>
        <moreinfo url="https://www.metacritic.com/game/playstation-3/the-last-of-us" />
    </game>

    <game>
        <title>God of War</title>
        <genre>Action-adventure</genre>
        <genre>Hack and slash</genre>
        <year>2018</year>
        <developer>Santa Monica Studio</developer>
        <metascore>94</metascore>
        <rules>
            <playerVersus>PvE</playerVersus>
            <numberOfPlayers>1</numberOfPlayers>
            <numberOfLives>∞</numberOfLives>
        </rules>
        <platform>PlayStation 4</platform>
        <platform>PC</platform>
        <moreinfo url="https://www.metacritic.com/game/playstation-4/god-of-war" />
    </game>

    <game>
        <title>Red Dead Redemption 2</title>
        <genre>Action-adventure</genre>
        <genre>Open-World</genre>
        <year>2018</year>
        <developer>Rockstar Studios</developer>
        <metascore>97</metascore>
        <rules>
            <playerVersus>PvE</playerVersus>
            <numberOfPlayers>1</numberOfPlayers>
            <numberOfLives>∞</numberOfLives>
        </rules>
        <platform>PlayStation 4</platform>
        <platform>Xbox One</platform>
        <platform>PC</platform>
        <platform>Google Stadia</platform>
        <moreinfo url="https://www.metacritic.com/game/playstation-4/red-dead-redemption-2" />
    </game>

</game_objects>
